<?php

/**
 * Implements hook_pay_method_handler_info().
 */
function authorizenet_pay_method_handler_info() {
  $path = drupal_get_path('module', 'authorizenet') . '/includes/handlers';
  return array(
    'pay_method_gateway_authorizenet' => array(
      'title' => t('Authorize.Net'),
      'description' => t('Payment processing using the Authorize.Net payment gateway'),
      'parent' => 'pay_method_gateway',
      'path' => $path,
    ),
  );
}

/**
 * Implementation of hook_theme().
 */
function authorizenet_theme() {
  module_load_include('theme.inc', 'authorizenet', 'theme/authorizenet');
  return authorizenet_theme_theme();
}

/**
 * Implements hook_pay_user_settings_access().
 */
function authorizenet_pay_user_settings_access() {
}

/**
 * Implements hook_pay_user_settings_form().
 */
function authorizenet_pay_user_settings_form(&$form, &$form_state) {
}

/**
 * Implements hook_pay_transaction_delete().
 */
function authorizenet_pay_transaction_delete(&$transaction) {
  // Delete any references to activities that will be deleted.
  db_query("DELETE FROM {authorizenet_pay_activity} WHERE paid IN
    (SELECT paid FROM {pay_activity} WHERE pxid = %d)", $transaction->pxid);
}

/**
 * List available Authorize.Net login profiles.
 */
function authorizenet_login_list($reset = TRUE) {
  static $list;
  if (!isset($list) || $reset) {
    $list = array();

    $res = db_query("SELECT id, name, developer FROM {authorizenet_login}
      WHERE uid IS NULL
      ORDER BY name");

    while ($row = db_fetch_object($res)) {
      $list[$row->id] = $row->name;
    }
  }

  return $list;
}

/**
 * Load an Authorize.Net login entry.
 */
function authorizenet_login_load($id = NULL) {
  require_once dirname(__FILE__) .'/includes/authorizenet.login.inc';

  if ($id) {
    $res = db_query("SELECT * FROM {authorizenet_login} WHERE id = %d", $id);
    if ($row = db_fetch_object($res)) {
      return New authorizenetLogin($row);
    }
  }
  else {
    return New authorizenetLogin();
  }
}

/**
 * Load an Authorize.Net object.
 */
function authorizenet($login, $sub = NULL, $account = NULL) {
  require_once dirname(__FILE__) .'/includes/authorizenet.inc';

  if (in_array($sub, array('cim', 'aim'))) {
    require_once dirname(__FILE__) .'/includes/authorizenet.' . $sub . '.inc';
    $class = 'Authorizenet' . $sub;
    return New $class($login, $account);
  }
  else {
    return New Authorizenet($login, $account);
  }
}

/**
 * Load a Authorize.Net payment profile for a given user.
 */
function authorizenet_profile($login, $sub = NULL, $account = NULL) {
  if (is_null($account)) {
    global $user;
    $account = $user;
  }

  $authorizenet = authorizenet($login, $sub);
  return $authorizenet->profile($account);
}
